# Generated by Django 3.1.3 on 2021-01-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_auto_20210107_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile'),
        ),
    ]
